- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs
    check:
      jobs:
        - ironic-dsvm-standalone
        - ironic-tempest-dsvm-functional-python2
        - ironic-tempest-dsvm-functional-python3
        - ironic-tempest-dsvm-bfv
        - ironic-tempest-dsvm-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        # Non-voting jobs
        - ironic-tempest-dsvm-ipa-wholedisk-bios-pxe_snmp-tinyipa:
            voting: false
        - ironic-tempest-dsvm-ironic-inspector:
            voting: false
        - ironic-tempest-dsvm-pxe_ipmitool-postgres:
            voting: false
        - openstack-tox-cover
    gate:
      queue: ironic
      jobs:
        - ironic-dsvm-standalone
        - ironic-tempest-dsvm-functional-python2
        - ironic-tempest-dsvm-functional-python3
        - ironic-tempest-dsvm-bfv
        - ironic-tempest-dsvm-ipa-partition-pxe_ipmitool-tinyipa-python3
        - ironic-tempest-dsvm-ipa-partition-redfish-tinyipa
        - ironic-tempest-dsvm-ipa-partition-uefi-pxe_ipmitool-tinyipa
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - openstack-tox-cover
    experimental:
      jobs:
        - ironic-dsvm-functional
    post:
      jobs:
        - openstack-tox-cover
