- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - openstack-python3-xena-jobs-arm64
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        - ironic-standalone
        - ironic-standalone-redfish
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos8-uefi
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-managed-non-standalone:
            voting: false
        - ironic-inspector-tempest-partition-bios-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-focal:
            voting: false
            override-checkout: master
        - bifrost-integration-redfish-vmedia-uefi-centos-8:
            voting: false
            override-checkout: master
        - ironic-tempest-pxe_ipmitool-postgres:
            voting: false
        - bifrost-benchmark-ironic:
            voting: false
    gate:
      queue: ironic
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-tempest-functional-python3
        - ironic-standalone
        - ironic-standalone-redfish
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-bios-ipmi-direct-tinyipa
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos8-uefi
    experimental:
      jobs:
        # TODO(dtantsur): these jobs are useful but currently hopelessly
        # broken. Fix them and bring back to the gate.
        - ironic-tempest-ipxe-ipv6:
            voting: false
        - ironic-grenade-multinode-multitenant:
            voting: false
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
