- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-ussuri-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-tempest-functional-python3
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-ipa-partition-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-indirect
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
        # Non-voting jobs
        - ironic-tox-bandit:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-pxe_snmp:
            voting: false
        - ironic-inspector-tempest:
            voting: false
        - ironic-inspector-tempest-managed:
            voting: false
        - ironic-inspector-tempest-partition-bios-redfish-vmedia:
            voting: false
        - ironic-tempest-ipa-wholedisk-bios-ipmi-direct-dib:
            voting: false
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - ironic-tempest-pxe_ipmitool-postgres:
            voting: false
        # NOTE(TheJulia): Marking non-voting as CI memory changes
        # means this job is unlikely to work without changing the base
        # ramdisk OS.
        # - ironic-tempest-ipa-partition-uefi-pxe_ipmitool:
        #    voting: false
        # NOTE(TheJulia): Tempest complains about invalid key, likely newer
        # tempest changes are no longer compatible with this version's
        # test. As this was already a test which had a high failure rate
        # due to dhcp issues, we are unlikely to fix it.
        # - ironic-tempest-ipxe-ipv6:
        #     voting: false
        # NOTE(TheJulia): high-ish failure rate due to memory footprint,
        # Commenting out for now.
        # - ironic-tempest-ipa-wholedisk-direct-tinyipa-multinode
    gate:
      jobs:
        - ironic-tox-unit-with-driver-libs
        - ironic-standalone
        - ironic-tempest-functional-python3
        - ironic-tempest-partition-bios-redfish-pxe
        - ironic-tempest-partition-uefi-redfish-vmedia
        - ironic-tempest-ipa-partition-pxe_ipmitool
        # Removing from voting due to memory consumption
        # - ironic-tempest-ipa-partition-uefi-pxe_ipmitool
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-tinyipa
        - ironic-tempest-ipa-wholedisk-bios-agent_ipmitool-indirect
        - ironic-tempest-ipa-partition-bios-agent_ipmitool-indirect
        - ironic-tempest-bfv
        - ironic-tempest-ipa-partition-uefi-pxe-grub2
        - metalsmith-integration-glance-localboot-centos7
    experimental:
      jobs:
        - ironic-inspector-tempest-discovery-fast-track:
            voting: false
